/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { WrappedMaticAbi } from "./WrappedMaticAbi";
export * as factories from "./factories";
export { WrappedMaticAbi__factory } from "./factories/WrappedMaticAbi__factory";
